### ISSUE TITLE
Mejorar botones de punto braille

### ISSUE THREAD

**Issue by lcapalbo** [braillear/braillear.github.io#7]
Letras QAZOKM en botones deberían ocultarse para pantallas chicas, asumiendo que van a usar touch.
Mostrar el punto braille que representa centrado en el botón (además de la letra, si es pantalla grande).
Usar botones estándar (gris), y aplicar estilo azul si está siendo presionado así hay un indicador visual más distinguible que el carácter braille que van formando en el display.

**Comment by mpielvitori** [comment]
Seguramente podés detectar si es touch o no para poner o no las letras Locutus.
Igual es un detalle mínimo :P

**Comment by lcapalbo** [comment]
Si si!
Lo tengo hecho:-D pero sin Internet hace 6 días... Cuando pueda comiteo,
hice montón de cambios.. Ya es Responsive, con mejor estilo. Puse caracter
braille de referencia y las letras se ven solo con pantallas mas grandes

Gracias!
